### ISSUE TITLE
IPv6 masking is incorrect

### ISSUE THREAD

**Issue by mlosapio** [apparentlymart/go-cidr#4]
There is an incorrect assumption on this line that the correct int to pass is `32`
https://github.com/apparentlymart/go-cidr/blob/master/cidr/cidr.go#L75

This is *not* the case in IPv6 and should be 128. 

Your package is used in the Terraform and as a result it's performing incorrect network calculations in their `cidrhost` function. 

I will append a crude patch which I believe solves the issue.

**Comment by apparentlymart** [comment]
Fixed by #5
