### ISSUE TITLE
add semver release

### ISSUE THREAD

**Issue by crasiak** [apparentlymart/go-cidr#6]
Hi, thanks for the package!

Would it be possible to create a release that follow's semver guildelines to use in our glide.yaml files? Even a 0.1.0 would be really helpful.

thanks!

**Comment by apparentlymart** [comment]
As part of making this repository function as a [Go module](https://github.com/golang/go/wiki/Modules) I've just tagged the latest `master` commit as `v1.0.0`. While my motivation here was to support native Go modules, I think this tag should also be usable by earlier dependency management tools like Glide.
